version: "2"
services:
  redis:
    image: "redis/redis-stack-server"
    env_file:
      - ./.env
    ports:
      - '127.0.0.1:${FC_REDIS_PORT}:${FC_REDIS_PORT}'
    command: redis-server --requirepass ${FC_REDIS_PASSWORD}
    